#ifndef _EVENTBUS_CONFIG_H_
#define _EVENTBUS_CONFIG_H_

#define EVENT_QUEUE_SIZE 20
#define EVENT_TASK_PRIO  5
#define EVENT_TASK_CORE  1

enum {
    MODULE_WIFI_NET = 0,
    MODULE_TESTER,
    MODULE_3,
    MODULE_4,
    MODULE_5,
    MODULES_MAX,
};

enum {
    CONFIG_WIFI_SSID = 0,
    CONFIG_WIFI_PASSWORD,

    CONFIG_MAX,
};

#endif /* _EVENTBUS_CONFIG_H_ */
